### PR TITLE
Updated to latest parent pom

### PR DESCRIPTION
**Pull request by g4s8**
#57 - updated to parent `0.3`, downgraded to JDK8

### CODE REVIEW

**Comment by g4s8** [comment]
@0crat assign @Sammers21

**Comment by 0crat** [comment]
> @0crat assign @Sammers21  ([here](https://github.com/artipie/http/issues/58#issuecomment-590836775))

@g4s8 This pull request [#58](https://github.com/artipie/http/issues/58) is assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ea4ce77c-40a5-4116-bd90-24a39800eb12); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job audit: performer @sammers21[/z](https://www.0crat.com/u/sammers21)[/z](https://www.0crat.com/u/sammers21) didn't make CR comments

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
