### PR TITLE
Using parent pom

### PR DESCRIPTION
**Pull request by g4s8**
Added pom parent to `pom.xml`

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#20](https://github.com/artipie/http/issues/20) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5e45e5e2-20e2-45ce-8df5-490a0ba583df); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/artipie/http/issues/20#issuecomment-582947010))

@g4s8 The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#20](https://github.com/artipie/http/issues/20), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/http#20` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
