### PR TITLE
#253 - RtRule.ByHeader created

### LINKED ISSUE #253: Create RtRule.ByHeader implementation
In pypi-adapter `RtRule` by header is required, so let's create such implementation. Implementation should filter requests by header name and value, it should be possible to filter values by regexps.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #253 
Implemented rule by headers.

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, looks good

**Comment by olenagerasimova** [comment]
@olegmoz please, do not merge yet

**Comment by olenagerasimova** [comment]
@olegmoz oh no, wrong alarm, sorry

**Comment by olegmoz** [comment]
@olenagerasimova okey, merging

**Comment by 0crat** [comment]
Job `gh:artipie/http#254` is not assigned, can't get performer

**Pull request merged**
