### PR TITLE
Another ctor to ResponseMatcher

### PR DESCRIPTION
**Pull request by olenagerasimova**
Added ctor with `IsHeader` to `ResponseMatcher`, this ctor will be used in docker-adapter to get rid of `new AllOf<>(ListOf<>(...))` repetitions.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#195](https://github.com/artipie/http/issues/195) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/4086ad9c-58c7-421d-a840-ee7af3f75c80); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f70bec93-eb39-47c2-b2f8-963b342d25d4, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:artipie/http#195" exists in boosts.xml, but the job is absent in the WBS among 60 jobs.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [323012b4-e7b1-4764-aba8-21b9d82b1068](https://www.0crat.com/footprint/CT2E6TK9B/323012b4-e7b1-4764-aba8-21b9d82b1068), Type: "Remove job from WBS"

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.13.1`

**Pull request merged**
