### PR TITLE
#156 - Added WWW-Authenticate header to SliceAuth response

### LINKED ISSUE #156: `AuthSlice` unauthorized response missing `WWW-Authenticate` header
Server should respond with 401 status and `WWW-Authenticate` header if requied authentication header is missing from response. This is by RFC, see https://tools.ietf.org/html/rfc7235#section-4.1
This behavior is expected by NuGet client

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #156 
Added WWW-Authenticate header to SliceAuth response

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#157](https://github.com/artipie/http/issues/157) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/255e4ecf-9ae7-4738-a1e3-ccb8c7cc1bf6); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
