### PR TITLE
#189 - Additional Headers constructors

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #189 
Added constructors to `Headers.From` class to build `Headers` from collection and additional header(s)

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#190](https://github.com/artipie/http/issues/190) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/eea77aee-dc62-49d3-a8b6-b8927398bf1d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@olegmoz please check failing build, it seems test coverage ratios goes down beyond min the threshold limits:
```
[WARNING] Rule violated for bundle http: lines covered ratio is 0.68, but expected minimum is 0.69
[WARNING] Rule violated for bundle http: complexity covered ratio is 0.61, but expected minimum is 0.62
```

**Comment by olegmoz** [comment]
@g4s8 added tests for the constructors, the coverage is fine now

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by g4s8** [comment]
@0crat quality bad

**Pull request merged**
