### PR TITLE
#145 - Added `Content-Length` checking related HTTP status codes

### LINKED ISSUE #145: Missing status codes for `Content-Length` checking
To properly implement https://github.com/artipie/artipie/issues/119 it is required to respond with status [413 Payload Too Large](https://tools.ietf.org/html/rfc7231#section-6.5.10) and maybe [411 Length Required](https://tools.ietf.org/html/rfc7231#section-6.5.11)

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #145 
Added 413 and 411 HTTP response status codes.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#146](https://github.com/artipie/http/issues/146) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/cbeb975c-8bda-433d-a024-391fea77e045); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/146#issuecomment-625720667))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#146](https://github.com/artipie/http/issues/146), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/http#146` is not assigned, can't get performer

**Pull request merged**
