### PR TITLE
Reorganized Github actions workflows files

### PR DESCRIPTION
**Pull request by g4s8**
#183 - reorganized Github actions workflows files, added experimental actions.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#184](https://github.com/artipie/http/issues/184) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/de06d13c-764d-42fe-bab0-1d2448c75a85); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/artipie/http/issues/184#issuecomment-651071894))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#184](https://github.com/artipie/http/issues/184), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/http#184` is not assigned, can't get performer

**Pull request merged**
