### PR TITLE
#153 - response matcher and test created

### PR DESCRIPTION
**Pull request by olenagerasimova**
Created response matcher for #153. This the same as #155

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#160](https://github.com/artipie/http/issues/160) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6fffa84e-6fee-4ef4-956b-d978bc1b46e1); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@paulodamaso I'm refusing, since this PR was reviewed in #155

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/http/issues/160#issuecomment-635224081))

@g4s8 Pull request [#160](https://github.com/artipie/http/issues/160) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:artipie/http#160` is not assigned, can't get performer

**Pull request merged**
