### PR TITLE
Cosmetic corrections in readme

### PR DESCRIPTION
**Pull request by olenagerasimova**
Made several cosmetic corrections in readme.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#111](https://github.com/artipie/http/issues/111) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/36d6ed1e-4b2b-41e8-aeca-f82efa0efe31); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/http/issues/111#issuecomment-610820236))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#111](https://github.com/artipie/http/issues/111), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/http#111` is not assigned, can't get performer

**Pull request merged**
