### PR TITLE
Added IT for slices

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #356
Added IT to illustrate the situation when Artipie stacks on the second request. Note, that slice should be introduced over `SliceRoute` and `RtRulePath` chain as `SliceSimple` with some response. If `SliceSimple` is replaced with a proper separate `Slice` implementation (as [AuthTokenSlice.java](https://github.com/artipie/conda-adapter/blob/master/src/main/java/com/artipie/conda/http/AuthTypeSlice.java) in conde for example) everything works properly.

Enable and run disabled test to see the problem.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@g4s8 please, could you take a look and help to understand where is the problem?

**Review by g4s8 — CHANGES_REQUESTED** [review]
@olenagerasimova it looks like a bug, can you create a ticket please and describe this issue there?

**Comment by olenagerasimova** [comment]
@g4s8 created #356

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Pull request merged**
