### PR TITLE
Extend AsyncResponse with constructor which accepts a single

### PR DESCRIPTION
**Pull request by Sammers21**
Improves AsyncReponse user experience.

### CODE REVIEW

**Comment by g4s8** [comment]
@Sammers21 why do we need it? I think it's better to use standard JDK classes for library API, e.g. `CompletableFuture` or `CompletionStage`

**Comment by Sammers21** [comment]
@g4s8 , Yes, we stick with `CompletableFuture` and `CompletionStage`, but I want to avoid an intermediate conversion operation. The avoidance improves resulted in user experience. Especially when this class is used in JRuby.

**Comment by 0crat** [comment]
Job `gh:artipie/http#130` is not assigned, can't get performer

**Comment by Sammers21** [comment]
@g4s8 , can you release a new version?

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.1`

**Pull request merged**
