### PR TITLE
Added 421 and 429 http response statuses

### LINKED ISSUE #243: Add 421 and 429 http response statuses
Let's add `421 Misdirected Request` and `429 Too Many Requests` response status to our enum.

### PR DESCRIPTION
**Pull request by EugeneLesnov**
Closes #243

### CODE REVIEW

**Comment by 0crat** [comment]
@EugeneLesnov this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by g4s8 — APPROVED** [review]
@EugeneLesnov thanks

**Comment by 0crat** [comment]
Job `gh:artipie/http#285` is not assigned, can't get performer

**Comment by EugeneLesnov** [comment]
@g4s8 have a nice day :)

**Pull request merged**
