### PR TITLE
Added response with body

### PR DESCRIPTION
**Pull request by g4s8**
#29 - added response with string and `ByteBuffer` body.

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by 0crat** [comment]
Job `gh:artipie/http#36` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job `gh:artipie/http#36` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Job `gh:artipie/http#36` doesn't exist in WBS, can't create order

**Pull request merged**
