### PR TITLE
Renamed front and fixed return type

### PR DESCRIPTION
**Pull request by g4s8**
#14 - renamed front and fixed return type

### CODE REVIEW

**Comment by g4s8** [comment]
@0crat status

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job `gh:artipie/http#15` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/http/issues/15#issuecomment-582317025))

@g4s8 This is what I know about this job in [CT2E6TK9B](https://www.0crat.com/p/CT2E6TK9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#15](https://github.com/artipie/http/issues/15) is [in scope](http://www.zerocracy.com/policy.html#14) for 14min
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fhttp%2315%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
