### PR TITLE
Implement publisher part

### PR DESCRIPTION
**Pull request by Sammers21**
This pull request is blocked by #91, and can't be reviewed or merged before. Related to #32

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#92](https://github.com/artipie/http/issues/92) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/43de27d0-b08d-4d89-a273-cb19d5bc35a9); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Sammers21** [comment]
@g4s8 , @Vatavuk , this pull request is ready for review

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/http/issues/92#issuecomment-604410475))

@g4s8 Job [#92](https://github.com/artipie/http/issues/92) is closed, can't start order

**Comment by 0crat** [comment]
Job audit: performer @vatavuk[/z](https://www.0crat.com/u/vatavuk)[/z](https://www.0crat.com/u/vatavuk) didn't make CR comments

**Pull request merged**
