### PR TITLE
Added toString() implementation to RsWithStatus so it will be easier …

### PR DESCRIPTION
**Pull request by olegmoz**
Added toString() implementation to RsWithStatus so it will be easier to see problem in tests

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 I'm available, please assign me

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:artipie/http#62` is not assigned, can't get performer

**Pull request merged**
